[pwsh.files]
"powershell/profile.ps1" = "~/OneDrive/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"powershell/abbr.ps1" = "~/.config/powershell/PSAbbreviations.ps1"
"powershell/commands.ps1" = "~/.config/powershell/commands.ps1"

[git.files]
"git/.gitconfig" = "~/.gitconfig"
[git.variables]
"ssh_public_key" = "~/.ssh/id_ed25519.pub"

[wezterm.files]
"wezterm/wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[scoop.files]
"scoop/config.json" = { target = "~/.config/scoop/config.json", type = "template" }

[zsh.files]
"zsh/.zshrc" = "~/.zshrc"

[zsh-config.files]
"zsh-config/macos.zsh" = "~/.zsh/macos.zsh"
"zsh-config/linux.zsh" = "~/.zsh/linux.zsh"
"zsh-config/windows.zsh" = "~/.zsh/windows.zsh"
"zsh-config/shared.zsh" = "~/.zsh/shared.zsh"

[mpv.files]
"mpv/config" = { target = "~/.config/mpv", type = "symbolic", recurse = true }

[act.files]
"act/.actrc" = "~/.actrc"

[atuin.files]
"atuin/config.toml" = "~/.config/atuin/config.toml"

[claude.files]
# Symbolic link on all files in the claude directory
"claude" = { target = "~/.claude", type = "symbolic", recurse = true }
