[git.variables]
"ssh_public_key" = 'C:\\Users\\kvnxiao\\.ssh\\id_ed25519.pub'

[mpv.files]
"mpv/config" = { target = "~/AppData/Roaming/mpv", type = "symbolic" }

[komorebi.files]
"komorebi/komorebi.json" = "~/komorebi.json"
"komorebi/komorebi.bar.json" = "~/komorebi.bar.json"
"komorebi/whkdrc" = "~/.config/whkdrc"

[windows-terminal.files]
"windows-terminal/settings.json" = { target = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json", type = "symbolic" }
